In [83]:
import numpy as np
import pandas as pd

In [84]:
df=pd.read_csv("IMDB Dataset.csv")

In [85]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [86]:
# Drop rows where sentiment is NaN (if there were other labels like 'neutral')
df = df.dropna(subset=['sentiment'])
df = df.dropna(subset=['review'])

In [87]:
df["sentiment"]=df["sentiment"].map({"positive":1, "negative": 0})

In [88]:
Y=df["sentiment"]
X=df["review"]

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.3, random_state=42)

In [90]:
# text vectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words="english", max_df=0.7)
X_train=vectorizer.fit_transform(X_train)
X_test=vectorizer.transform(X_test)

In [91]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [92]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,Y_train)

MultinomialNB()

In [93]:
Y_Pred=model.predict(X_test)

In [96]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(Y_test, Y_Pred))
print(classification_report(Y_test, Y_Pred))

Accuracy: 0.863
              precision    recall  f1-score   support

           0       0.85      0.88      0.86      7411
           1       0.88      0.85      0.86      7589

    accuracy                           0.86     15000
   macro avg       0.86      0.86      0.86     15000
weighted avg       0.86      0.86      0.86     15000

In [97]:
import joblib
joblib.dump(model, "sentiment_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']